### PR TITLE
Updated latest code and remove unwanted old code

### PR DESCRIPTION
**Pull request by mukeshpanchal27**

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
@jesselawson i have optimize coding and make media popup as per latest WordPress.

Please check it and let us know in case of any issue and merge it in WordPress repo

**Comment by mukeshpanchal27** [comment]
@jesselawson Have you checked this?

**Comment by mukeshpanchal27** [comment]
@jesselawson Any update on PR?

**Comment by jesselawson** [comment]
@mukeshpanchal27 Shoot I'm sorry I didn't get to this yet. Thanks for getting this back on my plate. I'll be able to pull this into my dev environment tonight and, based on what I'm seeing so far, likely pull it into master too! Thanks for the hard work.

**Comment by mukeshpanchal27** [comment]
@jesselawson Please check and let me know your feedback or any issue.

**Review by jesselawson — APPROVED** [review]

**Comment by mukeshpanchal27** [comment]
@jesselawson Have you pushed changes on WordPress.org plugin directory? I can't find the latest update there.

https://wordpress.org/plugins/easy-author-image/

**Pull request merged**
